apiVersion: batch/v1
kind: CronJob
metadata: 
   name: cronwala
spec:
   schedule: "*/1 * * * *"
   jobTemplate:
      spec:
        template:
          metadata:
             labels: 
               app: cronwala
          spec:
            restartPolicy: OnFailure
            containers: 
               - name: main
                 image: luksa/batch-job
