apiVersion: v1
kind: ReplicationController
metadata:
   name: myreplica
speac:
   replicas: 3
   selector:
       app: web
   template:
       metadata:
         labels:
            app: web
       spec:
        containers:
          - name: nginxcontainer
            image: nginx
            ports:
              - containerPort: 80
